services:
  - type: web
    name: prode-backend
    runtime: node
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prode-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_KEY
        generateValue: true
      - key: ADMIN_SEED_USER
        value: admin
      - key: ADMIN_SEED_PASS
        generateValue: true

  - type: web
    name: prode-frontend
    runtime: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: "" # completar despu√©s del deploy del backend (y hacer Rebuild)

databases:
  - name: prode-db
    databaseName: prode
    plan: free
